baseUrl = https://us-central1-kortana-test.cloudfunctions.net/app

### 


### 
POST https://us-central1-kortana-test.cloudfunctions.net/app/createUser 
Content-Type: application/json

{
    "phoneNumber": "0543892565",
    "password": "somepassword"
   

}

### 



POST https://us-central1-kortana-test.cloudfunctions.net/app/web3 